### ISSUE TITLE
Put freeglut in AOSP

### ISSUE THREAD

**Issue by AhmedX6** [arris69/FreeGlut-Android#1]
Hello,

I'm working on an AOSP. I would like to integrate freeglut to system.img.
I'm currently developping a custom surface on Android with OpenGl and I want to display some text so maybe GLUT can help do this.. But first of all I need to have the Android.mk that compiles all the sources directly on the Android Source Tree.

Please can you help me ?

**Comment by arris69** [comment]
sorry for late response, ist the issue on going?

**Comment by AhmedX6** [comment]
Hello no you can close :)
